
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.glowroot.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.glowroot.block.TorchWallBlock;
import net.mcreator.glowroot.block.TorchFloorBlock;
import net.mcreator.glowroot.block.TheRightSideBlock;
import net.mcreator.glowroot.block.RedstoneGlowFlashlightLightBlock;
import net.mcreator.glowroot.block.RedstoneFlashlightLightBlock;
import net.mcreator.glowroot.block.PureChrysopraseBlock;
import net.mcreator.glowroot.block.LockerAirBlock;
import net.mcreator.glowroot.block.LightDetectorBlock;
import net.mcreator.glowroot.block.LargeGlowFlowerBlock;
import net.mcreator.glowroot.block.InvisibleGlowrootBlockBlock;
import net.mcreator.glowroot.block.InvisibleGlowrootBlock3Block;
import net.mcreator.glowroot.block.InvisibleGlowrootBlock2Block;
import net.mcreator.glowroot.block.HardenedChysopraseBlock;
import net.mcreator.glowroot.block.GrowEmitterBlock;
import net.mcreator.glowroot.block.GlowshroomBlockBlock;
import net.mcreator.glowroot.block.GlowrootsBlock;
import net.mcreator.glowroot.block.GlowrootedStoneBlock;
import net.mcreator.glowroot.block.GlowrootedSmoothBasaltBlock;
import net.mcreator.glowroot.block.GlowrootedSmallBudBlock;
import net.mcreator.glowroot.block.GlowrootedMediumBudBlock;
import net.mcreator.glowroot.block.GlowrootedLargeBudBlock;
import net.mcreator.glowroot.block.GlowrootedCrystalizedBlockBlock;
import net.mcreator.glowroot.block.GlowrootedClusterBlock;
import net.mcreator.glowroot.block.GlowrootedCalciteBlock;
import net.mcreator.glowroot.block.GlowrootdirtBlock;
import net.mcreator.glowroot.block.GlowrootVentDuctBlock;
import net.mcreator.glowroot.block.GlowrootVentBlock;
import net.mcreator.glowroot.block.GlowrootUpgraderBlock;
import net.mcreator.glowroot.block.GlowrootTallWeedsBlock;
import net.mcreator.glowroot.block.GlowrootTNTBlock;
import net.mcreator.glowroot.block.GlowrootStoneWallBlock;
import net.mcreator.glowroot.block.GlowrootStoneStairsBlock;
import net.mcreator.glowroot.block.GlowrootStoneSlabBlock;
import net.mcreator.glowroot.block.GlowrootStonePressurePlateBlock;
import net.mcreator.glowroot.block.GlowrootStoneButtonBlock;
import net.mcreator.glowroot.block.GlowrootSpawnerBlock;
import net.mcreator.glowroot.block.GlowrootSeekerBlock;
import net.mcreator.glowroot.block.GlowrootRoseBlock;
import net.mcreator.glowroot.block.GlowrootRedstoneOreBlock;
import net.mcreator.glowroot.block.GlowrootPipe4WayBlock;
import net.mcreator.glowroot.block.GlowrootPipe2WayBlock;
import net.mcreator.glowroot.block.GlowrootPipe1WayBlock;
import net.mcreator.glowroot.block.GlowrootPillarBlock;
import net.mcreator.glowroot.block.GlowrootPanelBlock;
import net.mcreator.glowroot.block.GlowrootPaeoniaBlock;
import net.mcreator.glowroot.block.GlowrootNodeBlock;
import net.mcreator.glowroot.block.GlowrootMachineBlock;
import net.mcreator.glowroot.block.GlowrootLockerOpenBlock;
import net.mcreator.glowroot.block.GlowrootLockerBlock;
import net.mcreator.glowroot.block.GlowrootLitVentDuctBlock;
import net.mcreator.glowroot.block.GlowrootLeafBlock;
import net.mcreator.glowroot.block.GlowrootLaserEmitterBlock;
import net.mcreator.glowroot.block.GlowrootLapisOreBlock;
import net.mcreator.glowroot.block.GlowrootLamp9Block;
import net.mcreator.glowroot.block.GlowrootLamp8Block;
import net.mcreator.glowroot.block.GlowrootLamp7Block;
import net.mcreator.glowroot.block.GlowrootLamp6Block;
import net.mcreator.glowroot.block.GlowrootLamp5Block;
import net.mcreator.glowroot.block.GlowrootLamp4Block;
import net.mcreator.glowroot.block.GlowrootLamp3Block;
import net.mcreator.glowroot.block.GlowrootLamp2Block;
import net.mcreator.glowroot.block.GlowrootLamp1Block;
import net.mcreator.glowroot.block.GlowrootLamp15Block;
import net.mcreator.glowroot.block.GlowrootLamp14Block;
import net.mcreator.glowroot.block.GlowrootLamp13Block;
import net.mcreator.glowroot.block.GlowrootLamp12Block;
import net.mcreator.glowroot.block.GlowrootLamp11Block;
import net.mcreator.glowroot.block.GlowrootLamp10Block;
import net.mcreator.glowroot.block.GlowrootLadderBlock;
import net.mcreator.glowroot.block.GlowrootIronOreBlock;
import net.mcreator.glowroot.block.GlowrootGrateBlock;
import net.mcreator.glowroot.block.GlowrootGoldOreBlock;
import net.mcreator.glowroot.block.GlowrootFurnaceBlock;
import net.mcreator.glowroot.block.GlowrootFernBlock;
import net.mcreator.glowroot.block.GlowrootEmeraldOreBlock;
import net.mcreator.glowroot.block.GlowrootDoorBlock;
import net.mcreator.glowroot.block.GlowrootDiamondOreBlock;
import net.mcreator.glowroot.block.GlowrootDandelionBlock;
import net.mcreator.glowroot.block.GlowrootCrystalizedBlockBlock;
import net.mcreator.glowroot.block.GlowrootCoreBlock;
import net.mcreator.glowroot.block.GlowrootCoppeOreBlock;
import net.mcreator.glowroot.block.GlowrootConcreteBlock;
import net.mcreator.glowroot.block.GlowrootCoalOreBlock;
import net.mcreator.glowroot.block.GlowrootChainBlock;
import net.mcreator.glowroot.block.GlowrootCattailBlock;
import net.mcreator.glowroot.block.GlowrootCartBlock;
import net.mcreator.glowroot.block.GlowrootBricksBlock;
import net.mcreator.glowroot.block.GlowrootBrickWallBlock;
import net.mcreator.glowroot.block.GlowrootBrickStairsBlock;
import net.mcreator.glowroot.block.GlowrootBrickSlabBlock;
import net.mcreator.glowroot.block.GlowrootBlockBlock;
import net.mcreator.glowroot.block.GlowrootBarsBlock;
import net.mcreator.glowroot.block.GlowrootAstilbesBlock;
import net.mcreator.glowroot.block.GlowrootAlliumBlock;
import net.mcreator.glowroot.block.GlowingRunesBlock;
import net.mcreator.glowroot.block.GlowWeedsBlock;
import net.mcreator.glowroot.block.GlowRunesBlock;
import net.mcreator.glowroot.block.GlowRootLanternBlock;
import net.mcreator.glowroot.block.GlowRootEndBlock;
import net.mcreator.glowroot.block.GlowRootBlock;
import net.mcreator.glowroot.block.GlowPoppyBlock;
import net.mcreator.glowroot.block.GlowMushroomBlock;
import net.mcreator.glowroot.block.GlowGlassPaneBlock;
import net.mcreator.glowroot.block.GlowGlassBlock;
import net.mcreator.glowroot.block.GlowFlowerBlock;
import net.mcreator.glowroot.block.GlowFlashlightLightBlock;
import net.mcreator.glowroot.block.GlowEmitterBlock;
import net.mcreator.glowroot.block.GlowDetectorBlock;
import net.mcreator.glowroot.block.GlowBulbBlock;
import net.mcreator.glowroot.block.FlashlightLightBlock;
import net.mcreator.glowroot.block.EmitterFlaskBlockBlock;
import net.mcreator.glowroot.block.DazzlerBlock;
import net.mcreator.glowroot.block.DarknessDetectorBlock;
import net.mcreator.glowroot.block.CutGlowrootStairsBlock;
import net.mcreator.glowroot.block.CutGlowrootSlabBlock;
import net.mcreator.glowroot.block.CutGlowrootBlock;
import net.mcreator.glowroot.block.ChrysopraseDustSplatBlock;
import net.mcreator.glowroot.block.ChiseledGlowrootPillarBlock;
import net.mcreator.glowroot.block.ChiseledGlowrootBricksBlock;
import net.mcreator.glowroot.block.CavePainting1Block;
import net.mcreator.glowroot.block.ArtificialGlowrootedBlock2Block;
import net.mcreator.glowroot.block.ArtificialGlowrootBlock2Block;
import net.mcreator.glowroot.block.ArtificalGlowrootedBlockBlock;
import net.mcreator.glowroot.block.ArtificalGlowrootedBlock3Block;
import net.mcreator.glowroot.block.ArtificalGlowrootBlockBlock;
import net.mcreator.glowroot.block.ArtificalGlowrootBlock3Block;
import net.mcreator.glowroot.block.AlarmoffBlock;
import net.mcreator.glowroot.block.AlarmOnBlock;
import net.mcreator.glowroot.GlowrootMod;

public class GlowrootModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, GlowrootMod.MODID);
	public static final RegistryObject<Block> GLOW_ROOT = REGISTRY.register("glow_root", () -> new GlowRootBlock());
	public static final RegistryObject<Block> GLOW_WEEDS = REGISTRY.register("glow_weeds", () -> new GlowWeedsBlock());
	public static final RegistryObject<Block> GLOWROOT_TALL_WEEDS = REGISTRY.register("glowroot_tall_weeds", () -> new GlowrootTallWeedsBlock());
	public static final RegistryObject<Block> GLOWROOT_FERN = REGISTRY.register("glowroot_fern", () -> new GlowrootFernBlock());
	public static final RegistryObject<Block> GLOWROOT_ASTILBES = REGISTRY.register("glowroot_astilbes", () -> new GlowrootAstilbesBlock());
	public static final RegistryObject<Block> GLOW_POPPY = REGISTRY.register("glow_poppy", () -> new GlowPoppyBlock());
	public static final RegistryObject<Block> GLOWROOT_ROSE = REGISTRY.register("glowroot_rose", () -> new GlowrootRoseBlock());
	public static final RegistryObject<Block> GLOW_FLOWER = REGISTRY.register("glow_flower", () -> new GlowFlowerBlock());
	public static final RegistryObject<Block> GLOWROOT_PAEONIA = REGISTRY.register("glowroot_paeonia", () -> new GlowrootPaeoniaBlock());
	public static final RegistryObject<Block> GLOWROOT_ALLIUM = REGISTRY.register("glowroot_allium", () -> new GlowrootAlliumBlock());
	public static final RegistryObject<Block> GLOWROOT_DANDELION = REGISTRY.register("glowroot_dandelion", () -> new GlowrootDandelionBlock());
	public static final RegistryObject<Block> GLOWROOT_CATTAIL = REGISTRY.register("glowroot_cattail", () -> new GlowrootCattailBlock());
	public static final RegistryObject<Block> LARGE_GLOW_FLOWER = REGISTRY.register("large_glow_flower", () -> new LargeGlowFlowerBlock());
	public static final RegistryObject<Block> GLOWSHROOM = REGISTRY.register("glowshroom", () -> new GlowMushroomBlock());
	public static final RegistryObject<Block> GLOW_BULB = REGISTRY.register("glow_bulb", () -> new GlowBulbBlock());
	public static final RegistryObject<Block> GLOWROOT_LEAVES_FALLEN = REGISTRY.register("glowroot_leaves_fallen", () -> new GlowrootsBlock());
	public static final RegistryObject<Block> GLOWROOT_LEAVES = REGISTRY.register("glowroot_leaves", () -> new GlowrootLeafBlock());
	public static final RegistryObject<Block> GLOWROOTED_STONE = REGISTRY.register("glowrooted_stone", () -> new GlowrootedStoneBlock());
	public static final RegistryObject<Block> GLOWROOTDIRT = REGISTRY.register("glowrootdirt", () -> new GlowrootdirtBlock());
	public static final RegistryObject<Block> GLOWROOT_COAL_ORE = REGISTRY.register("glowroot_coal_ore", () -> new GlowrootCoalOreBlock());
	public static final RegistryObject<Block> GLOWROOT_COPPE_ORE = REGISTRY.register("glowroot_coppe_ore", () -> new GlowrootCoppeOreBlock());
	public static final RegistryObject<Block> GLOWROOT_IRON_ORE = REGISTRY.register("glowroot_iron_ore", () -> new GlowrootIronOreBlock());
	public static final RegistryObject<Block> GLOWROOT_GOLD_ORE = REGISTRY.register("glowroot_gold_ore", () -> new GlowrootGoldOreBlock());
	public static final RegistryObject<Block> GLOWROOT_LAPIS_ORE = REGISTRY.register("glowroot_lapis_ore", () -> new GlowrootLapisOreBlock());
	public static final RegistryObject<Block> GLOWROOT_REDSTONE_ORE = REGISTRY.register("glowroot_redstone_ore", () -> new GlowrootRedstoneOreBlock());
	public static final RegistryObject<Block> GLOWROOT_DIAMOND_ORE = REGISTRY.register("glowroot_diamond_ore", () -> new GlowrootDiamondOreBlock());
	public static final RegistryObject<Block> GLOWROOT_EMERALD_ORE = REGISTRY.register("glowroot_emerald_ore", () -> new GlowrootEmeraldOreBlock());
	public static final RegistryObject<Block> GLOWROOT_STONE_STAIRS = REGISTRY.register("glowroot_stone_stairs", () -> new GlowrootStoneStairsBlock());
	public static final RegistryObject<Block> GLOWROOT_STONE_SLAB = REGISTRY.register("glowroot_stone_slab", () -> new GlowrootStoneSlabBlock());
	public static final RegistryObject<Block> GLOWROOT_STONE_WALL = REGISTRY.register("glowroot_stone_wall", () -> new GlowrootStoneWallBlock());
	public static final RegistryObject<Block> GLOWROOT_STONE_BUTTON = REGISTRY.register("glowroot_stone_button", () -> new GlowrootStoneButtonBlock());
	public static final RegistryObject<Block> GLOWROOT_STONE_PRESSURE_PLATE = REGISTRY.register("glowroot_stone_pressure_plate", () -> new GlowrootStonePressurePlateBlock());
	public static final RegistryObject<Block> GLOWROOT_BRICKS = REGISTRY.register("glowroot_bricks", () -> new GlowrootBricksBlock());
	public static final RegistryObject<Block> GLOWROOT_BRICK_STAIRS = REGISTRY.register("glowroot_brick_stairs", () -> new GlowrootBrickStairsBlock());
	public static final RegistryObject<Block> GLOWROOT_BRICK_SLAB = REGISTRY.register("glowroot_brick_slab", () -> new GlowrootBrickSlabBlock());
	public static final RegistryObject<Block> GLOWROOT_BRICK_WALL = REGISTRY.register("glowroot_brick_wall", () -> new GlowrootBrickWallBlock());
	public static final RegistryObject<Block> CHISELED_GLOWROOT_BRICKS = REGISTRY.register("chiseled_glowroot_bricks", () -> new ChiseledGlowrootBricksBlock());
	public static final RegistryObject<Block> CUT_GLOWROOT = REGISTRY.register("cut_glowroot", () -> new CutGlowrootBlock());
	public static final RegistryObject<Block> CUT_GLOWROOT_STAIRS = REGISTRY.register("cut_glowroot_stairs", () -> new CutGlowrootStairsBlock());
	public static final RegistryObject<Block> CUT_GLOWROOT_SLAB = REGISTRY.register("cut_glowroot_slab", () -> new CutGlowrootSlabBlock());
	public static final RegistryObject<Block> GLOWROOT_CONCRETE = REGISTRY.register("glowroot_concrete", () -> new GlowrootConcreteBlock());
	public static final RegistryObject<Block> GLOWROOT_PILLAR = REGISTRY.register("glowroot_pillar", () -> new GlowrootPillarBlock());
	public static final RegistryObject<Block> GLOWROOT_GRATE = REGISTRY.register("glowroot_grate", () -> new GlowrootGrateBlock());
	public static final RegistryObject<Block> THE_RIGHT_SIDE = REGISTRY.register("the_right_side", () -> new TheRightSideBlock());
	public static final RegistryObject<Block> GLOWROOT_PANEL = REGISTRY.register("glowroot_panel", () -> new GlowrootPanelBlock());
	public static final RegistryObject<Block> GLOWROOT_VENT_DUCT = REGISTRY.register("glowroot_vent_duct", () -> new GlowrootVentDuctBlock());
	public static final RegistryObject<Block> GLOWROOT_LIT_VENT_DUCT = REGISTRY.register("glowroot_lit_vent_duct", () -> new GlowrootLitVentDuctBlock());
	public static final RegistryObject<Block> ALARMOFF = REGISTRY.register("alarmoff", () -> new AlarmoffBlock());
	public static final RegistryObject<Block> GLOWROOT_LOCKER = REGISTRY.register("glowroot_locker", () -> new GlowrootLockerBlock());
	public static final RegistryObject<Block> GLOWROOT_CART = REGISTRY.register("glowroot_cart", () -> new GlowrootCartBlock());
	public static final RegistryObject<Block> GLOWROOT_VENT = REGISTRY.register("glowroot_vent", () -> new GlowrootVentBlock());
	public static final RegistryObject<Block> GLOWROOT_DOOR = REGISTRY.register("glowroot_door", () -> new GlowrootDoorBlock());
	public static final RegistryObject<Block> GLOWROOT_LADDER = REGISTRY.register("glowroot_ladder", () -> new GlowrootLadderBlock());
	public static final RegistryObject<Block> GLOWROOT_BARS = REGISTRY.register("glowroot_bars", () -> new GlowrootBarsBlock());
	public static final RegistryObject<Block> GLOWROOT_CHAIN = REGISTRY.register("glowroot_chain", () -> new GlowrootChainBlock());
	public static final RegistryObject<Block> GLOWROOT_BLOCK = REGISTRY.register("glowroot_block", () -> new GlowrootBlockBlock());
	public static final RegistryObject<Block> GLOW_ROOT_LANTERN = REGISTRY.register("glow_root_lantern", () -> new GlowRootLanternBlock());
	public static final RegistryObject<Block> GLOW_RUNES = REGISTRY.register("glow_runes", () -> new GlowRunesBlock());
	public static final RegistryObject<Block> GLOWING_RUNES = REGISTRY.register("glowing_runes", () -> new GlowingRunesBlock());
	public static final RegistryObject<Block> ARTIFICAL_GLOWROOT_BLOCK_1 = REGISTRY.register("artifical_glowroot_block_1", () -> new ArtificalGlowrootBlockBlock());
	public static final RegistryObject<Block> ARTIFICIAL_GLOWROOT_BLOCK_2 = REGISTRY.register("artificial_glowroot_block_2", () -> new ArtificialGlowrootBlock2Block());
	public static final RegistryObject<Block> ARTIFICAL_GLOWROOT_BLOCK_3 = REGISTRY.register("artifical_glowroot_block_3", () -> new ArtificalGlowrootBlock3Block());
	public static final RegistryObject<Block> GLOWROOT_UPGRADER = REGISTRY.register("glowroot_upgrader", () -> new GlowrootUpgraderBlock());
	public static final RegistryObject<Block> GLOWROOT_MACHINE = REGISTRY.register("glowroot_machine", () -> new GlowrootMachineBlock());
	public static final RegistryObject<Block> GLOWROOT_NODE = REGISTRY.register("glowroot_node", () -> new GlowrootNodeBlock());
	public static final RegistryObject<Block> GLOW_EMITTER = REGISTRY.register("glow_emitter", () -> new GlowEmitterBlock());
	public static final RegistryObject<Block> LIGHT_DETECTOR = REGISTRY.register("light_detector", () -> new LightDetectorBlock());
	public static final RegistryObject<Block> DARKNESS_DETECTOR = REGISTRY.register("darkness_detector", () -> new DarknessDetectorBlock());
	public static final RegistryObject<Block> GROW_EMITTER = REGISTRY.register("grow_emitter", () -> new GrowEmitterBlock());
	public static final RegistryObject<Block> GLOWROOT_SEEKER = REGISTRY.register("glowroot_seeker", () -> new GlowrootSeekerBlock());
	public static final RegistryObject<Block> GLOW_GLASS = REGISTRY.register("glow_glass", () -> new GlowGlassBlock());
	public static final RegistryObject<Block> GLOW_GLASS_PANE = REGISTRY.register("glow_glass_pane", () -> new GlowGlassPaneBlock());
	public static final RegistryObject<Block> GLOWROOT_TNT = REGISTRY.register("glowroot_tnt", () -> new GlowrootTNTBlock());
	public static final RegistryObject<Block> GLOWSHROOM_BLOCK = REGISTRY.register("glowshroom_block", () -> new GlowshroomBlockBlock());
	public static final RegistryObject<Block> UNPURE_CHRYSOPRASE = REGISTRY.register("unpure_chrysoprase", () -> new PureChrysopraseBlock());
	public static final RegistryObject<Block> PURE_CHYSOPRASE = REGISTRY.register("pure_chysoprase", () -> new HardenedChysopraseBlock());
	public static final RegistryObject<Block> BLOCK_OF_CHRYSOPRASE = REGISTRY.register("block_of_chrysoprase", () -> new GlowrootCrystalizedBlockBlock());
	public static final RegistryObject<Block> BUDDED_BLOCK_OF_CHRYSOPRASE = REGISTRY.register("budded_block_of_chrysoprase", () -> new GlowrootedCrystalizedBlockBlock());
	public static final RegistryObject<Block> CHRYSOPRASE_CLUSTER = REGISTRY.register("chrysoprase_cluster", () -> new GlowrootedClusterBlock());
	public static final RegistryObject<Block> LARGE_CHRYSOPRASE_BUD = REGISTRY.register("large_chrysoprase_bud", () -> new GlowrootedLargeBudBlock());
	public static final RegistryObject<Block> MEDIUM_CHRYSOPRASE_BUD = REGISTRY.register("medium_chrysoprase_bud", () -> new GlowrootedMediumBudBlock());
	public static final RegistryObject<Block> SMALL_CHRYSOPRASE_BUD = REGISTRY.register("small_chrysoprase_bud", () -> new GlowrootedSmallBudBlock());
	public static final RegistryObject<Block> GLOWROOT_CORE = REGISTRY.register("glowroot_core", () -> new GlowrootCoreBlock());
	public static final RegistryObject<Block> CAVE_PAINTING_1 = REGISTRY.register("cave_painting_1", () -> new CavePainting1Block());
	public static final RegistryObject<Block> CHRYSOPRASE_DUST_SPLAT = REGISTRY.register("chrysoprase_dust_splat", () -> new ChrysopraseDustSplatBlock());
	public static final RegistryObject<Block> EMITTER_FLASK_BLOCK = REGISTRY.register("emitter_flask_block", () -> new EmitterFlaskBlockBlock());
	public static final RegistryObject<Block> GLOW_ROOT_END = REGISTRY.register("glow_root_end", () -> new GlowRootEndBlock());
	public static final RegistryObject<Block> GLOW_DETECTOR = REGISTRY.register("glow_detector", () -> new GlowDetectorBlock());
	public static final RegistryObject<Block> GLOWROOT_LAMP_1 = REGISTRY.register("glowroot_lamp_1", () -> new GlowrootLamp1Block());
	public static final RegistryObject<Block> GLOWROOT_LAMP_2 = REGISTRY.register("glowroot_lamp_2", () -> new GlowrootLamp2Block());
	public static final RegistryObject<Block> GLOWROOT_LAMP_3 = REGISTRY.register("glowroot_lamp_3", () -> new GlowrootLamp3Block());
	public static final RegistryObject<Block> GLOWROOT_LAMP_4 = REGISTRY.register("glowroot_lamp_4", () -> new GlowrootLamp4Block());
	public static final RegistryObject<Block> GLOWROOT_LAMP_5 = REGISTRY.register("glowroot_lamp_5", () -> new GlowrootLamp5Block());
	public static final RegistryObject<Block> GLOWROOT_LAMP_6 = REGISTRY.register("glowroot_lamp_6", () -> new GlowrootLamp6Block());
	public static final RegistryObject<Block> GLOWROOT_LAMP_7 = REGISTRY.register("glowroot_lamp_7", () -> new GlowrootLamp7Block());
	public static final RegistryObject<Block> GLOWROOT_LAMP_8 = REGISTRY.register("glowroot_lamp_8", () -> new GlowrootLamp8Block());
	public static final RegistryObject<Block> GLOWROOT_LAMP_9 = REGISTRY.register("glowroot_lamp_9", () -> new GlowrootLamp9Block());
	public static final RegistryObject<Block> GLOWROOT_LAMP_10 = REGISTRY.register("glowroot_lamp_10", () -> new GlowrootLamp10Block());
	public static final RegistryObject<Block> GLOWROOT_LAMP_11 = REGISTRY.register("glowroot_lamp_11", () -> new GlowrootLamp11Block());
	public static final RegistryObject<Block> GLOWROOT_LAMP_12 = REGISTRY.register("glowroot_lamp_12", () -> new GlowrootLamp12Block());
	public static final RegistryObject<Block> GLOWROOT_LAMP_13 = REGISTRY.register("glowroot_lamp_13", () -> new GlowrootLamp13Block());
	public static final RegistryObject<Block> GLOWROOT_LAMP_14 = REGISTRY.register("glowroot_lamp_14", () -> new GlowrootLamp14Block());
	public static final RegistryObject<Block> GLOWROOT_LAMP_15 = REGISTRY.register("glowroot_lamp_15", () -> new GlowrootLamp15Block());
	public static final RegistryObject<Block> INVISIBLE_GLOWROOT_BLOCK_1 = REGISTRY.register("invisible_glowroot_block_1", () -> new InvisibleGlowrootBlockBlock());
	public static final RegistryObject<Block> ARTIFICAL_GLOWROOTED_BLOCK_1 = REGISTRY.register("artifical_glowrooted_block_1", () -> new ArtificalGlowrootedBlockBlock());
	public static final RegistryObject<Block> ARTIFICAL_GLOWROOTED_BLOCK_3 = REGISTRY.register("artifical_glowrooted_block_3", () -> new ArtificalGlowrootedBlock3Block());
	public static final RegistryObject<Block> INVISIBLE_GLOWROOT_BLOCK_3 = REGISTRY.register("invisible_glowroot_block_3", () -> new InvisibleGlowrootBlock3Block());
	public static final RegistryObject<Block> ARTIFICIAL_GLOWROOTED_BLOCK_2 = REGISTRY.register("artificial_glowrooted_block_2", () -> new ArtificialGlowrootedBlock2Block());
	public static final RegistryObject<Block> INVISIBLE_GLOWROOT_BLOCK_2 = REGISTRY.register("invisible_glowroot_block_2", () -> new InvisibleGlowrootBlock2Block());
	public static final RegistryObject<Block> DAZZLER = REGISTRY.register("dazzler", () -> new DazzlerBlock());
	public static final RegistryObject<Block> GLOWROOT_FURNACE = REGISTRY.register("glowroot_furnace", () -> new GlowrootFurnaceBlock());
	public static final RegistryObject<Block> GLOWROOT_LOCKER_OPEN = REGISTRY.register("glowroot_locker_open", () -> new GlowrootLockerOpenBlock());
	public static final RegistryObject<Block> GLOWROOT_PIPE_1_WAY = REGISTRY.register("glowroot_pipe_1_way", () -> new GlowrootPipe1WayBlock());
	public static final RegistryObject<Block> GLOWROOT_PIPE_2_WAY = REGISTRY.register("glowroot_pipe_2_way", () -> new GlowrootPipe2WayBlock());
	public static final RegistryObject<Block> GLOWROOT_PIPE_4_WAY = REGISTRY.register("glowroot_pipe_4_way", () -> new GlowrootPipe4WayBlock());
	public static final RegistryObject<Block> TORCH_FLOOR = REGISTRY.register("torch_floor", () -> new TorchFloorBlock());
	public static final RegistryObject<Block> TORCH_WALL = REGISTRY.register("torch_wall", () -> new TorchWallBlock());
	public static final RegistryObject<Block> FLASHLIGHT_LIGHT = REGISTRY.register("flashlight_light", () -> new FlashlightLightBlock());
	public static final RegistryObject<Block> REDSTONE_FLASHLIGHT_LIGHT = REGISTRY.register("redstone_flashlight_light", () -> new RedstoneFlashlightLightBlock());
	public static final RegistryObject<Block> GLOW_FLASHLIGHT_LIGHT = REGISTRY.register("glow_flashlight_light", () -> new GlowFlashlightLightBlock());
	public static final RegistryObject<Block> REDSTONE_GLOW_FLASHLIGHT_LIGHT = REGISTRY.register("redstone_glow_flashlight_light", () -> new RedstoneGlowFlashlightLightBlock());
	public static final RegistryObject<Block> GLOWROOTED_CALCITE = REGISTRY.register("glowrooted_calcite", () -> new GlowrootedCalciteBlock());
	public static final RegistryObject<Block> GLOWROOTED_SMOOTH_BASALT = REGISTRY.register("glowrooted_smooth_basalt", () -> new GlowrootedSmoothBasaltBlock());
	public static final RegistryObject<Block> ALARM_ON = REGISTRY.register("alarm_on", () -> new AlarmOnBlock());
	public static final RegistryObject<Block> GLOWROOT_SPAWNER = REGISTRY.register("glowroot_spawner", () -> new GlowrootSpawnerBlock());
	public static final RegistryObject<Block> CHISELED_GLOWROOT_PILLAR = REGISTRY.register("chiseled_glowroot_pillar", () -> new ChiseledGlowrootPillarBlock());
	public static final RegistryObject<Block> GLOWROOT_LASER_EMITTER = REGISTRY.register("glowroot_laser_emitter", () -> new GlowrootLaserEmitterBlock());
	public static final RegistryObject<Block> LOCKER_AIR = REGISTRY.register("locker_air", () -> new LockerAirBlock());
}
